replicaCount: 1

image:
  repository: registry.rwcloud.org/websocket
  pullPolicy: IfNotPresent
  tag: "latest"
  pullSecrets:
    - name: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: websocket-test.rwcloud.org
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - hosts:
        - websocket-test.rwcloud.org
      secretName: websocket-test-tls

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleUpCooldownPeriod: 60
  scaleDownCooldownPeriod: 60 